* Craft a snap notes
Link to the [[https://documentation.ubuntu.com/snapcraft/stable/tutorials/craft-a-snap/][docs]].

My goal is to learn how to build a snap and this tuorial seems to teach it from start to end using python.

** Overview
In this tutorial, we'll build a snap package for a Python app called pyfiglet. The concepts we'll cover transfer to both simple and complex snaps. We'll cover everything from creating the build environment and the configuration file, to troubleshooting missing libraries and finding which interfaces to open.

It should take 20 minutes to complete.

You won't need to come prepared with deep knowledge of software packaging, but familiarity with Linux paradigmes and terminal operations is required.

Once you complete this tutorial, you'll have experience hand-crafting snaps that serves as the basis for further work with creating snaps.

** Lession Plan
Put simple, this tutorial is a run-through os the process of constructing a snap. We show you how to:

- Start a snap project from scratch
- State the project's essential information
- Define the project source files and main program
- Package the snap
- Modify the build process to enchance the snap's contents
- Share root files with snap

** What we'll work with
The object of this tutorial is to package [[https://github.com/pwaller/pyfiglet][pyfiglet]] as a personal test snap. It's a lightweight app for displaying text as ASCII art, and is simple to build and test.

The snap will be named /ukuzama-pyfiglet/, after a fictional user. Throughout this code replace /ukuzama/ with your own username.

** What you'll need
For this tutorial, you'll need:
- An x64 system running Ubuntu 22.04 of Ubuntu 24.04
- A local user with super user privileges
- 20GB of free space

** Install Snapcraft and LXD
*** Before you install
If you have a Docker installation, you might run into conflicts with LXD over the course of this tutorial. As a remedy, you can let Snapcraft build with Multipass instead. To do so, start a fresh terminal session and run:
~SNAPCRAFT_BUILD_ENVIRONMENT=multipass~
Then, proceed to begin the project.

**** What is Multipass (Multipass vs Docker)?
Multipass is a tool for creating and managing lightweight virtual machines, primarily for running Ubuntu, while Docker is a platform for developing, shipping, and running applications in containers. If you need a full VM environment, Multipass is suitable, but for containerization application, Docker is the better choice. 

*** Installation
Snapcraft is itself available as a snap. LEt's begin by installing it. In ther terminal, run:

~snap install snapcraft --classic~

Next, let's add LXD to your system. It functions as the build provider and containerizees the build environment.

~snap install lxd~

You also need to add you local user account to the ~lxd~ group so you can access the tool's resources:

~sudo usermod -a -G lxd $USER~

Log out and back in to your account for the new group to become active. Then, check that you're a member of the group by running:

~groups $USER~

Look for lxd in the output.

Finally, initilize LXD with a lightweight, default configuration:
~sudo lxd init --auto~

** Begin the Project
Every snap project resides in its own directory. Start by creating one in a development space on your system (My project is called crazcalm-pyfiglet).

A snap is defined in a declarative ~snapcraft.yaml~ file, called the /project file/. By constructing the file key by key, we'll be building the snap's particulars. Snapcraft has an ~init~ command that spawns a template project file. Let's start with that:

~snapcraft init~

From here onward, we'll be working primarily in the project file. Open ~snap/snapcraft.yaml~ in a text editor.

** Define the package information
The first section inside a snap project file is typically its package information, sometimes informally referred to as its metadata. This information tells both humans and machines avout the snap, such as its purpose, authors, license, and so on. The comments in the template describe how to use these keys.

Replace the top section with:
#+begin_src text
name: ukuzama-pyfiglet
base: core24
version: "0.1"
summary: pyfiglet is a program for making large letters out of ordinary text
description: |
  pyfiglet is a full port of FIGlet (http://www.figlet.org/) into pure python.
  It takes ASCII text and renders it in ASCII art fonts (like the title above,
  which is the 'block' font).

  This snap is not endorsed by the pyfiglet project.
#+end_src

As this is a personal snap, we prepended the project name with a user name. You might encounter other snaps in the Snap Store with naming that follows this pattern -- it's the recommended format, to keep personal copies of snaps distinct from their originals.

We didn't alter the ~base~ key, since we want our project to be built on top of the lastest Ubuntu LTS release.

Since we're packaging a project authored by someone else, we ought to respect their intentions and thinking in the description keys. So, we reused them. The ~summary~ is a short description with a had limit of 79 characters, but nothing like that is present in the pyfiglet README. Instead, we sourced one from the upstream project at [[http://www.figlet.org/][figlet.org]]. The fuller ~description~ key, which has no length limit, is taken form pyfiglet. We added a disclaimer about endorsement at the end.

** Define the target platforms
As we're building on an x64 system, and we're only running basic tests for this tutorial, we should contrain our snap to only build on the current CPU architecture, AMD64. At a later point, when you're able to test on other platforms, you could widen the coverage in this configuration.

Add the ~platform~ key after the project information:
#+begin_src text
  platforms:
    amd64:
#+end_src

With the declaration, Snapcraft will only build the snap on AMD64 machines, for AMD64 machines. Take care to preserve the colon (:) in ~amd64:~.

*** Will amd64 work on intel?
I looked it up and the answer is yes. Amd64 builds created with Snapcraft are compatible with Intel processors, as both use the same x86-64 architecture. Most modern Intel CPUs can run these builds without issues.

** Define the main part
A /part/ is either a piece of software that we want to build from source or a clump of files. In either case, the purpose of a part is to bundle files from a source into a snap. Usually they're version-controlled components of the project itself, but you can aggregate them from a variety of locations.

For the ~parts~ key, add an entry for our main part, the ~pyfiglet~ source code.

#+begin_src text
parts:
  pyfiglet:
    plugin: python
    source-type: git
    source: https://github.com/snapcraft-docs/pyfiglet
#+end_src

Parts have three important keys worth discussing.

We set ~plugin~ to ~python~ because pyfiglet is a Python project and we watn to build it from source.

We set ~source-type~ to ~git~ because the project is stored as a Git repository.

We set ~source~ to the remote location of the project. Some software projects take responsibility for their own snaps, and store their own ~snapcraft.yaml~ file in the source code. With pyfiglet, we're merely handling the packaging on the project's behalf, meaning our project file is downstream of and dependent on it. By pointing to a remote URL, Snapcraft willl download the source before it packs the snap.

*** pyfiglet source code thoughts
The last paragraph confused me a bit, so I looked at the pyfiglet source code for clarity.

They do not have a snapcraft.yaml file. There project is a installable python cli package. There is nothing special about it.

** Pack the snap
