* Aretha Franklin I dreamed a dream story
** Overview
I was listening to a cassette of Aretha Franklin on my way from the our local vet. I am passively listening when all the lyrics start to sound familar in words, but not in vocals. It took a second for me to recongize it, but I was listening to I dreamed a dream from Les miserables! My immediate thought was like, which one came first?! It turns out Aretha did a cover of Les Miserables in <TODO -- look up info. I think she also sang it for the president hahah>.

Video should be short. 30 seconds or less.

Note: I do not think that I am allowed to play the music, so I will have to use descriptive language to describe her version of the song.

** Tone
Quorky story meant to keep the audience enganged and off balance with random facts

*** Some random facts
- wear my crotchet headphones, but don't explain then.
- work cassette/cassette player into the video somehow
- Possibly include that I am picking up medicine from the local vet for a friend 
