* Textual
[[https://textual.textualize.io/][Textual]], according to their website, is a =/Rapid Application Development/= framework for Python. Build sophisticated user interfaces with a simple Python API. Run you apps in the terminal or a web browser.

Note: I'm looking at this for the terminal aspect. I was completely unaware that these apps could also be ran in the brower.

** Tutorial: Stopwatch Application
We're going to build a stopwatch application. This application should show a list of stopwatches with buttons to start, stop and reset the stopwatches. We also want the user to be able to add and remove stopwatches as required.

*** App Class
The first step in building a Textual app is to import and extend the App class. Here's a basic app class we will use as a starting point for the stopwatch app.

#+BEGIN_SRC python
   from textual.app import App, ComposeResult
   from textual.widgets import Footer, Header

   class StopwatchApp(App):
       """A Textual app to manage stopwatches."""
       BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

       def compose(self) -> ComposeResult:
           """Create children widgets for the app."""
           yield Header()
           yield Footer()

       def action_toggle_dark(self) -> None:
           """An action to toggle dark mode."""
           self.theme = (
               "textual-dark" if self.theme == "textual-light" else "textual-light"
           )

  If __name__ == "__main__":
      app = StopwatchApp()
      app.run()
#+END_SRC

Hit the =~D~= Key to toggle between light and dark themes.
Hit =~Ctrl + Q~= to exit the app and return to the command prompt.

*** A Closer Look at the App class
The first line imports =~App~= class, which is the base class for all Textual apps. The second line imports two builtin widgets: =~Footer~=, which shows a bar at the bottom of the screen with bound keys, and =~Header~= which shows a title at the top of the screen.

Widgets are re-usable components responsible for managing a part of the screen. We will cover how to build widgets in this tutorial.

The App class is were most of the logic of Textual app is written. It is responsible for loading configuration, setting up widgets, handling keys, and more.

Here's what the above app defines:

- =~BINDINGS~= is a list of tuples that maps (or binds) keys to actions in your app. The first value in the tuple is the key; the second value is the name of the action; the final value is a short description. We have a single binding which maps the =~D~= key on to the "toggle_dark" action. See the [[https://textual.textualize.io/guide/input/#bindings][key bindings]] in the guid for details.

  - =~compose()~= is where we construct a user interface with widgets. The =~compose()~= method may return a list of widgets, but it is generally easier to =/yield/= thme (making this method a generator). In the example code we yield an instance of each of the widget classes we imported.

  - =~action_toggle_dark()~= definea an action method. Actions are methods beginning with =~action_~= followed by the name of the action. The =~BINDINGS~= list above tells Textual to run this action when the user hits the  =~D~= key. See [[https://textual.textualize.io/guide/actions/][actions]] in the guide for details.

*** Designing a UI with Widgets
Textual has a large number of [[https://textual.textualize.io/widget_gallery/][builtin widgets]]. For our app, we will need new widgets, which we can create by extending and combining the builtin widgets.

**** Custom Widgets
We need a =~Stopwatch~= widget compose of the following widgets:
- A "Start" button
- A "Stop" button
- A "Reset" button
- A time display

  Let's add those to the app. Just a skeleton for now, we will add the rest of the features as we go.

  #+BEGIN_SRC python
            from textual.app import App, ComposeResult
            from textual.containeers import HorizontalGroup, VerticalScroll
            from textual.widgets import Button, Digits, Footer, Header

            class TimeDisplay(Digits):
                """a widget to display elapsed time."""

            class Stopwatch(HorizontalGroup):
                """A stopwatch widget."""
                def compose(self) -> ComposeResult:
                    """Create children wdigets of a stopwatch."""
                    yield Button("Start", id="start", variant="success")
                    yield Button("Stop", id="stop", variant="error")
                    yield Button("Reset", id="reset")
                    yield TimeDisplay("00:00:00.00")

        class StopwatchApp(App):
            """A Textual app to manage stopwatches."""
            BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

            def compose(self) -> ComposeResult:
                """Create children widgets for the app"""
                yield Header()
                yield Footer()
                yield VericalScroll(Stopwatch(), Stopwatch(), Stopwatch())

            def action_toggle_dark(self) -> None:
                """An action to toggle dark mode."""
                self.theme = (
                    "textual-dark" if self.theme == "textual-light" else "textual-light"
                )

    if __name__ == "__main__":
        app = StopwatchApp()
        app.run()
  #+END_SRC

  We've imported two new widgets in this code: =~Button~= for the buttons and =~Digits~= for the time display. Additionally, we've imported =~HorizontalGroup~= and =~VerticalScroll~= from =~textual.containers~= (as the name of the module suggests, containers are widgets which contain other widgets). We will use these container widgets to define the general layout of our interface.

  The =~TimeDisplay~= is currently very simple, all it does is extend =~Digits~= without adding any new features. We will flesh this out later.

  The =~Stopwatch~= widget class extends the =~HorizontalGroup~= container class, which will arrange its children int a horizontal row. The Stopwatch's =~compose()~= adds those children, which correspond to the components from the scketch above.

***** Coordinating Widgets
If you are builing custom widgets of your own, be sure to see thee guide on [[https://textual.textualize.io/guide/widgets/#coordinating-widgets][coordinating widgets]].

**** The buttons
The Button constructor takes a label to be displayed in the button. Additionally, some of the buttons set the following parameters:
- =~id~= is an identifier we can ise to tell the buttons apart in the code and apply styles.
- =~variant~= is a string which selects a default style. The "success" variant makes the button green, and the "error" variant makes it red.

**** Composing the widgets
The new line in =~StopwatchApp.compose()~= yields a single =~VerticalScroll~= which will scroll if the contents don't quite fit. The widgets also takes care of key bindings required for scrolling like up, down, page down, pafe up, home, end, etc.

When widgets contain other widgets (like =~VeritcalScroll~=) they will typically accept their children widgets as positinal arguments. So the line =~yield VerticalScroll(Stopwatch(), Stopwatch(), Stopwatch())~= creates a =~VerticalScroll~= containing three =~Stopwatch~= widgets.

**** Writing Textual CSS
Every widget has a =~styles~= object with a number of attributes that impact how the widget will appear. Here's how you might set white text and a blue background for a widget:

#+BEGIN_SRC python
  self.styles.background = "blue"
self.styles.color = "white"
#+END_SRC

While it's possible to set all styles for an app thi way, it is rarely necessary. Textual has support for CSS (Cascading Style Sheets). CSS files are data files loaded by your app which contain information about styles to apply to your widgets.

CSS makes it easy to iterate on the desgin of your app and enables live-editing.

#+BEGIN_SRC python
  ...
  class StopwatchApp(App):
      CSS_PATH = "stopwatch02.tcss"
      ...
#+END_SRC

Adding the =~CSS_PATH~= class variable tells Textual to load the following file when the app starts:

#+BEGIN_SRC css
  Stopwatch {
      background: $boost;
      height: 5;
      margin: 1;
      min-width: 50;
      padding: 1;
  }

  TimeDisplay {
      text-align: center;
      color: $foreground-muted;
      height: 3;
  }

  Button {
      width: 16;
  }

  #start {
      dock: left;
  }

  #stop {
      dock: left;
      display: none;
  }

  #resset {
      dock: right;
  }
#+END_SRC

***** CSS Basics
CS files contain a mumber of =/declaration blocks/=.
#+BEGIN_SRC css
Stopwatch {
      background: $boost;
      height: 5;
      margin: 1;
      min-width: 50;
      padding: 1;
  }
#+END_SRC

The first line tells Textual that the styles should apply to the =~Stopwatch~= widget (Note: The Stopwatch widget inherits from the Horizontal Widget, so the CSS statments apply to the Horizontal Widget layout).

- =~background: $boost~= sets the background colot to =~$boost~=. The =~$~= prefix picks a pre-defined color from the builtin theme. There are other ways to specify colors such as =~"blue"~= or =~rgb(20,46,210)~=.

- =~height: 5~= sets the hieght of our widget to 5 lines of text.
- =~margin: 1~= sets a margin of 1 cell aorund the =~Stopwatch~= widget to create a little space between widgets in the list.
- =~min-width: 50~= sets the minimum width of our widget to 50 cells.
- =~padding: 1~= sets a padding of 1 cell around the children widgets.

  Here is the rest of the CSS file:
  #+BEGIN_SRC css
 TimeDisplay {
      text-align: center;
      color: $foreground-muted;
      height: 3;
  }

  Button {
      width: 16;
  }

  #start {
      dock: left;
  }

  #stop {
      dock: left;
      display: none;
  }

  #resset {
      dock: right;
  }
  #+END_SRC

  The =~TimeDisplay~= block aligns the text to the center (=~text-align:~=), sets its color (=~color:~=), and sets it height (=~height:~=) to 3 lines.

  The =~Button~= block sets the width (=~width:~=) of the buttond to 16 cells (character widths).

  The last 3 blocks have a slightl different format. When the declaration begins with a =~#~= then the styles will be applied to widgets with a matching "id" atribute. We've set an ID on the =~Button~= widgets we yielded i the =~compose~=.

  The buttons have a =~dock~= style which aligns the widget to a given edge. The start and stop buttons are dockeked to the left edge, while the reset button is docked to the right edge.

  You may hace noticed that the stop button as =~display: none;~=. This tells Textual to not show the button. We do this because we don't want to display th stop button when the timer is not running. Similarly, we don't want to show the starrt button when the timer is running. We will cover how to manage such dynamic user interfaces in the next section.

***** Dynamic CSS
We want out =~Stopwatch~= widget to have two states: a default state with a Start and Reset button; and a =/started/= state with a Stop button. When a stopwatch is started it should also have a green background to indicate it is currently active.

We can accomplish this with a CSS class. A widget may have any number of CSS classes, which may be added and removed to change its appearance.

Here is the additional CSS classes:
#+BEGIN_SRC css
  .started {
      background: $success-muted;
      color: $text;
  }

  .started TimeDisplay {
      color: $foreground;
  }

  .started #start {
      display: none;
  }

  .started #stop {
      display: block;
  }

  .started #reset {
      visibility: hidden;
  }
#+END_SRC

These new ruls are prefixed with =~.started~=. The =~.~= indicates that =~.started~= refers to a CSS class called "started."

Some of the new styles have more than one selector separated by a space. The space indicats that the rule should match the second selector if it is a child of the first.

**** Manipulating classes
Modifying a widget's CSS classes is a convenient way to update visuals without introducting a lot of messy display related code.

You can add and remove CSS classes with the =~add_class()~= and =~remove_class()~= mthods. We will use these methods to connect the started state to the Start/Stop buttons.

The following code will start or stop the stopwatches in response to clicking a button:

#+BEGIN_SRC python
    from textual.app import App, ComposeResult
    from textual.containers import HorizontalGRoup, VeritcalScroll
    from textual.widgets import Button, Dgits, Footer, Header

    class TimmeDisplay(Digits):
        """A widget to display elapsed time."""

    class Stopwatch(HorizotalGroup):
        """A stopwatch widget."""

        def on_button_pressed(self, event: Button.Pressed) -> None:
            """Event handler called when a button is pressed."""
            if event.button.id == "start":
                self.add_class("started")
            elif event.button.id == "stop":
                self.remove_class("started")

        def compose(self) -> ComposeResult:
            """Create children widgets of a Stopwatch."""
            yield Button("Start", id="start", variant="success")
            yield Button("Stop", id="stop", variant="error")
            yield Button("Reset", id="reset")
            yield TimeDisplay("00:00:00.00")

    class StopwatchApp(App):
        """A textual app to manage stopwatches."""
        CSS_PATH = "stopwatch04.tcss"
        BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

        def compose(self) -> ComposeResult:
            """Create children widgets for the app."""
            yield Header()
            yield Footer()
            yield VerticalScroll(Stopwatch(), Stopwatch(), Stopwatch())

        def action_toggle_dark(self) -> None:
            """An action to toggle dark mode."""
            self.theme = (
                "textual-dark" if self.theme == "textual-light" else "textual-light"
            )


  if __name__ == "__main__":
      app  = StopwatchApp()
      app.run()
#+END_SRC

The =~on_button_pressed~= mthod is an =/event_handler/=. Event handlers are methods called by Textual in response t an event such as a key press, mouse click, etc. Event hanflers begine with =~on_~= followed by the name of the event they will handle. Hence =~on_button_pressed~= will handle the button pressed event.

See the guide on  [[https://textual.textualize.io/guide/events/#message-handlers][message handlers]] fo the details on how to write event handlers.

**** Reactive attributes
A recurring them in Textual is that you rarely ned to explicitly update a widget's visuals. It is possible: you can call =~refresh()~= to display new data. However, Textual prefers to do this automatically via =/reactive/= attributes.

Reactive attributes work like any other attribute, such as those you might set in an =~__init__~= method, but allow Textual to detect when you assign them, in addition to some other superpowers.

To add a reactive attribute, import reactive and create an instance in you class scop.

Let's add reactivs to out stopwatch to calculated and display the elasped time.

#+BEGIN_SRC python
   ...
   from textual.reactive import reactive
   ...
   class TimeDisplay(Digits):
       """A widget to display elasped time."""
       start_time = reactive(monotonic)
       time = reactive(0.0)

       def on_mont(self) -> None:
           """Event handler called when widget is added to the app. """
           self.set_interval(1/60, self.update_time)
           
       def update_time(self) -> None:
           """Method to update the time to the current time."""
           self.time = monotonic() - self.start_time

       def watch_time(self, time: float) -> None:
           """Called when the time attribute changes."""
           minute, seconds = divmod(time, 60)
           hours, minutes = divmod(minutes, 60)
           self.update(f"{hours:02.0f}:{minutes:02.0f}:{seconds:05.2f}")

  class Stopwatch(HorizontalGroup):
      ...
      def compose(self) -> ComposeResult:
          ...
          yield TimeDisplay()
          ...

 ...
#+END_SRC

We have added two reactive attributes to the =~TimeDisplay~= widget: =~start_time~= will contain the time the stopwatch was started (in seconds), and =~time~= wil contain the time to be displayed in the =~Stopwatch~= widget.

Both attributes will be available on =~self~= as if you had assigned them in =~__init__~=. If you write to either of these attributes widgets will update automatically.

The first argument to =~reactive~= may be a default value for the attribute or a callable that returns a default value. We set the default for =~start_time~= to the =~monotonic~= function which will be called to initialize the attribute with the current time when the =~TimeDisplay~= is added to the app. The =~time~= attribute has a simple float as the default, so =~self.time~= will be initialized to =~0~=.

The =~on_mount~= method is an event handler called when the widget is first added to the application. In this method we call =~set_interval()~= to create a timer which calls =~self.update_time~= sixty time a second. This =~update_time~= method calculates the time elasped since the widget started and assigns it to =~self.time~= -- which brings us to one of the Reactive's super-powers.

If you implement a method that begins with =~watch_~= followed by the name of a reactive attribute, then the method will be caled when the attriute is modified. Such methods are known as =/watch/= methods.

Because =~watch_time~= watches the =~time~= attribute, when we update =~self.time~= 60 times a second we also implicitly call =~watch_time~= which converts the elapssed time to a string and updates the widget with a call to =~self.update~=.

**** Wiring butons
We need to be able to start, stop and reset each stopwatch independently. We can do this by adding a few more methods to the =~TimeDisplay~= class.

#+BEGIN_SRC python
   from time import monotonic

   from textual.app import App, ComposeResult
   from textual.containers import HorizontalGroup, VerticalScroll
   from textual.reactive import reactive
   from textual.widgets import Button, Digits, Footer, Header

   class TimeDispay(Digits):
       """A widget to display elapsed time."""
       start_time = reactive(monotonic)
       time = reactive(0.0)
       total = reactive(0.0)

       def on_mount(self) -> None:
           """Event handler called when widget is added to the app."""
           self.update_timer = self.set_interval(1/60, self.update_time, pause=True)

       def update_time(self) -> None:
           """Method to update time to current."""
           self.time = self.total + (monotonic() - self.start_time)

       def watch_tim(self, time: float) -> None:
           """Called when the time attribute changes."""
           minutes, seconds = divmod(time, 60)
           hours, minutes = divmod(minutes, 60)
           self.update(f"{hours:02.0f}: {minutes:02.0f}: {seconds:05.2f})"

        def start(self) -> None:
            """Method to start (or resume) time updating."""
            self.start_time = monotonic()
            sself.update_timer.resume()

       def stop(self) -> None:
           """Method to stop the time display updating."""
           self.update_timer.pause()
           self.total += monotonic() = self.start_time
           self.time = self.total

       def reset(self) -> None:
           """Method to reset the time display to zero."""
           self.total = 0
           self.time = 0

  class Stopwatch(HorzontalGroup):
      """A stopwatch widget"""
      def on_button_pressed(self, event: Button.Pressed) -> None:
          """Event handler called when a button is pressed."""
          button_id = event.button.id
          time_display = self.query_one(TimeDisplay)
          if button_id == "start":
              time_display.start()
              self.add_class("started")
          elif button == "stop":
              time_display.stop()
              self.remove_class("started")
          elif button_id == "reset":
              time_display.reset()

      def compose(self) -> CompseResult:
         """Create children widgets of a stopwatch"""
         yield Button("Start", id="start", variant="success")
         yield Button("Stop", id="stop", variant="error")
         yield Button("Reset", id="reset")
         yield TimeDisplay()


  class StopwatchApp(App):
      """A Textual appmto manage stopwatches."""
      CSS_PATH = "stopwatch04.tcss"
      BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

     def compose(self) -> ComposeResult:
         """Call to add widgets to the app."""
         yield Header()
         yield Footer()
         yield VerticalScroll(Stopwatch(), Stopwatch, Stopwatch)

    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.theme = (
            "textual-dark" if self.theme == "textual-light" else "textual-light"
        )


  if __name__ == "__main__":
      app = StopwatchApp()
      app.run()
#+END_SRC

**** Dynamic widgets
The Stopwatch app creates widgets when it starts via the =~compose~= method. We will also need to create new widgets while the ap is running, and remove widgetswe no longer need. We can do this by calling =~mount()~= to add a widget and =~remove()~= to remove a widget.

#+BEGIN_SRC python
  ...
  class StopwatchApp(App):
      CSS_PATH = "stopwatch.tcss"
      BINDINGS[
          ("d", "toggle_dark", "Toggle dark mode"),
          ("a", "add_stopwatch", "Add"),
          ("r", "remove_stopwatch", "Remove"),
      ]

      def compose(self) -> ComposeResult:
          yield Header()
          yield Footer()
          yield VeriticalSroll(Stopwatch(), Stopwatch(), Stopwatch, id="timers")

      def action_add_stopwatch(self) -> None:
          """An action to add a timer."""
          new_stopwatch = Stopwatch()
          self.query_one("#timers").mount(new_stopwatch)
          new_stopwatch.scroll_visible()

      def action_remove_stopwatch(self) -> None:
          """Called to remove a timer."""
          timer = self.query("Stopwatch")
          if timers:
              timers.last().remove()

         ...
#+END_SRC

The =~action_add_stopwatch~= method creates and mounts a new stopwatch. Note the call to =~query_one~= with a CSS selector of =~"#timeers"~= which gets the timer's container via its ID. Once mounted, the new Stopwatch will appear in the terminal. That last line in =~action_add_stopwatch~= calls =~scroll_visible()~= which will scroll the container to make the new Stopwatch visible (if required).

